const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"../dist");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
for(const file of ["styles.css","model.js","app.js","manifest.webmanifest","favicon.svg","icon-192.svg","icon-512.svg","sw.js"])assert.ok(fs.existsSync(path.join(root,file)),`${file} ausente`);
for(const id of ["nom-i11","nom-i12","nom-i21","nom-i22","assist","calculate-fixed"])assert.ok(html.includes(`id="${id}"`),`${id} ausente`);
for(const id of ["nom-v","rc1","rc2","nom-i11","nom-i12","nom-i21","nom-i22","live-v"]){
  assert.match(html,new RegExp(`id="${id}"[^>]*step="0\\.01"`),`${id} debe variar en centésimas`);
}
assert.ok(!html.includes("<svg"),"el esquema en vivo no debe mostrarse");
assert.ok(!html.includes('type="range"'),"no debe haber reglas deslizantes");
const app=fs.readFileSync(path.join(root,"app.js"),"utf8");
const css=fs.readFileSync(path.join(root,"styles.css"),"utf8");
assert.ok(app.includes('const ids=["11","12","21","22"]'));
assert.ok(app.includes('id="reo-${id}"'));
assert.ok(app.includes('id="system-r-${id}"'),"cada resistencia del sistema debe ser editable");
assert.ok(app.includes('$(`system-r-${id}`).addEventListener("input",solve)'),"editar una resistencia debe recalcular la simulación");
assert.ok(!app.includes("data-set-reo"),"no debe haber botones de valores rápidos");
assert.ok(!app.includes("reo-range"),"no debe haber reóstatos deslizantes");
assert.ok(!app.includes("% del objetivo"),"la desviación no debe mostrarse en las tarjetas");
assert.ok(app.includes("Resistencia del Sistema R${id}"),"debe identificar la resistencia del sistema");
assert.ok(app.includes('id="reo-power-${id}"'),"debe mostrar la potencia de cada reóstato");
assert.ok(app.includes("o.currents[id]**2*o.rheostats[id]"),"debe calcular P=I²·Reo");
assert.ok(app.includes('<span class="input-title">Corriente</span>'),"debe usar el título Corriente");
assert.ok(app.includes('>0.00 W</strong>'),"debe mostrar la potencia junto a ReoXX");
assert.ok(app.includes("value.toFixed(2)"),"la potencia debe mostrar dos decimales con punto");
assert.ok(!app.includes("Corriente objetivo"),"debe eliminar el título anterior de corriente");
assert.ok(!app.includes("Potencia del reóstato"),"debe eliminar la fila separada de potencia");
assert.ok(css.includes(".more-actions{position:static;grid-column:1/-1;width:100%}"),"Más opciones debe desplegarse dentro del panel visible");
const manifest=JSON.parse(fs.readFileSync(path.join(root,"manifest.webmanifest"),"utf8"));
assert.equal(manifest.display,"standalone");
assert.equal(manifest.start_url,"./");
assert.equal(manifest.short_name,"ANODEFLEX 2 1INY");
assert.ok(html.includes("2 ramas · 1 inyección"),"debe mostrar el nombre nuevo");
console.log("Pruebas de la aplicación estática: correctas");
